apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mongodb # Select pods with label app=mongodb
  ports:
    - protocol: TCP
      port: 27017 # Service Port
      targetPort: 27017 # Pods Port